// Generated by gencpp from file xipiter_ros/AddTwoInts.msg
// DO NOT EDIT!


#ifndef XIPITER_ROS_MESSAGE_ADDTWOINTS_H
#define XIPITER_ROS_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <xipiter_ros/AddTwoIntsRequest.h>
#include <xipiter_ros/AddTwoIntsResponse.h>


namespace xipiter_ros
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace xipiter_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xipiter_ros::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::xipiter_ros::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::xipiter_ros::AddTwoInts > {
  static const char* value()
  {
    return "xipiter_ros/AddTwoInts";
  }

  static const char* value(const ::xipiter_ros::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::xipiter_ros::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::xipiter_ros::AddTwoInts >
template<>
struct MD5Sum< ::xipiter_ros::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::xipiter_ros::AddTwoInts >::value();
  }
  static const char* value(const ::xipiter_ros::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::xipiter_ros::AddTwoIntsRequest> should match
// service_traits::DataType< ::xipiter_ros::AddTwoInts >
template<>
struct DataType< ::xipiter_ros::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::xipiter_ros::AddTwoInts >::value();
  }
  static const char* value(const ::xipiter_ros::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xipiter_ros::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::xipiter_ros::AddTwoInts >
template<>
struct MD5Sum< ::xipiter_ros::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::xipiter_ros::AddTwoInts >::value();
  }
  static const char* value(const ::xipiter_ros::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::xipiter_ros::AddTwoIntsResponse> should match
// service_traits::DataType< ::xipiter_ros::AddTwoInts >
template<>
struct DataType< ::xipiter_ros::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::xipiter_ros::AddTwoInts >::value();
  }
  static const char* value(const ::xipiter_ros::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XIPITER_ROS_MESSAGE_ADDTWOINTS_H
